INSERT INTO products (productID, productCategory, prodName, prodDescription, prodImageURL, inventoryCount, price)
VALUES
("wfr1-1-0", "WomenRollOnFragrance", "Black Woman", "Women's Roll On Fragrance - 1oz", "dbImages/wfr1-1-0.png", "100", "13.00"),
("wfr2-1-0", "WomenRollOnFragrance", "Chloe Love", "Women's Roll On Fragrance - 1oz", "dbImages/wfr2-1-0.png", "100", "13.00"),
("wfr3-1-0", "WomenRollOnFragrance", "Crush", "Women's Roll On Fragrance - 1oz", "dbImages/wfr3-1-0.png", "100", "13.00"),
("wfr4-1-0", "WomenRollOnFragrance", "Gucci Guilty", "Women's Roll On Fragrance - 1oz", "dbImages/wfr4-1-0.png", "100", "13.00"),
("wfr5-1-0", "WomenRollOnFragrance", "Pink Friday", "Women's Roll On Fragrance - 1oz", "dbImages/wfr5-1-0.png", "100", "13.00"),
("wfr6-1-0", "WomenRollOnFragrance", "Pleasures", "Women's Roll On Fragrance - 1oz", "dbImages/wfr6-1-0.png", "100", "13.00"),
("wfr7-1-0", "WomenRollOnFragrance", "Red Door", "Women's Roll On Fragrance - 1oz", "dbImages/wfr7-1-0.png", "100", "13.00"),
("wfr8-1-0", "WomenRollOnFragrance", "Si", "Women's Roll On Fragrance - 1oz", "dbImages/wfr8-1-0.png", "100", "13.00"),
("wfr9-1-0", "WomenRollOnFragrance", "Beautiful", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr10-1-0", "WomenRollOnFragrance", "Bloomin Bouquet", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr11-1-0", "WomenRollOnFragrance", "Burberry Summer", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr12-1-0", "WomenRollOnFragrance", "Burberry Weekend", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr13-1-0", "WomenRollOnFragrance", "Cashmere Mist", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr14-1-0", "WomenRollOnFragrance", "Bombshell", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr15-1-0", "WomenRollOnFragrance", "Chanel Chance", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr16-1-0", "WomenRollOnFragrance", "Dolce & Cabana Light Blue", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr17-1-0", "WomenRollOnFragrance", "Ed Hardy", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr18-1-0", "WomenRollOnFragrance", "Ellen Tracy", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr19-1-0", "WomenRollOnFragrance", "Egyptian Musk", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr20-1-0", "WomenRollOnFragrance", "Euphoria", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr21-1-0", "WomenRollOnFragrance", "Fancy Love", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr22-1-0", "WomenRollOnFragrance", "Flower Bomb", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr23-1-0", "WomenRollOnFragrance", "Happy", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr24-1-0", "WomenRollOnFragrance", "Heavenly Dream Angel", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr25-1-0", "WomenRollOnFragrance", "Issy Miyake", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr26-1-0", "WomenRollOnFragrance", "J'Adore", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr27-1-0", "WomenRollOnFragrance", "JOY", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr28-1-0", "WomenRollOnFragrance", "LA VIE ESTE Belle", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr29-1-0", "WomenRollOnFragrance", "Miami Blossom", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr30-1-0", "WomenRollOnFragrance", "Michelle Obama", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr31-1-0", "WomenRollOnFragrance", "Michelle Obama 2", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr32-1-0", "WomenRollOnFragrance", "Paris Hilton", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr33-1-0", "WomenRollOnFragrance", "Pattie Labelle", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr34-1-0", "WomenRollOnFragrance", "Perry Ellis '360'", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr35-1-0", "WomenRollOnFragrance", "Pretty & Purple", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr36-1-0", "WomenRollOnFragrance", "Scented Peace", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),
("wfr37-1-0", "WomenRollOnFragrance", "White Linen", "Women's Roll On Fragrance - 1oz", "dbImages/noImage.png", "100", "13.00"),

("mfr1-1-0", "MenRollOnFragrance", "ABSOLU", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr2-1-0", "MenRollOnFragrance", "Bad Boy", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr3-1-0", "MenRollOnFragrance", "Boucheron", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr4-1-0", "MenRollOnFragrance", "Bond # 9 NYC", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr5-1-0", "MenRollOnFragrance", "Carlos Santana", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr6-1-0", "MenRollOnFragrance", "Chanel", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr7-1-0", "MenRollOnFragrance", "Chrome", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr8-1-0", "MenRollOnFragrance", "Cool Water", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr9-1-0", "MenRollOnFragrance", "Creed Adventus", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr10-1-0", "MenRollOnFragrance", "Creed Silver", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr11-1-0", "MenRollOnFragrance", "D&G King", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr12-1-0", "MenRollOnFragrance", "D&G Light", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr13-1-0", "MenRollOnFragrance", "Desire Blue", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr14-1-0", "MenRollOnFragrance", "Dolce & Gabanna", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr15-1-0", "MenRollOnFragrance", "Egyptian Musk", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr16-1-0", "MenRollOnFragrance", "Golden Sands", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr17-1-0", "MenRollOnFragrance", "Gucci Guilty", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr18-1-0", "MenRollOnFragrance", "I AM King", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr19-1-0", "MenRollOnFragrance", "Invictus", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr20-1-0", "MenRollOnFragrance", "Invictus Aqua", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr21-1-0", "MenRollOnFragrance", "Issy Miyake", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr22-1-0", "MenRollOnFragrance", "Jaipur", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr23-1-0", "MenRollOnFragrance", "Jean Paul Gautier", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr24-1-0", "MenRollOnFragrance", "Jimmy Choo", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr25-1-0", "MenRollOnFragrance", "Jimmy Choo Blue", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr26-1-0", "MenRollOnFragrance", "Jimmy Choo Urban Hero", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr27-1-0", "MenRollOnFragrance", "LaCoste", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr28-1-0", "MenRollOnFragrance", "Obama", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr29-1-0", "MenRollOnFragrance", "Polo Black", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr30-1-0", "MenRollOnFragrance", "Polo Blue", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr31-1-0", "MenRollOnFragrance", "Polo Supreme", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),
("mfr32-1-0", "MenRollOnFragrance", "Sauvage", "Men's Roll On Fragrance - 1oz", "dbImages/noImage.png", "15", "13.00"),

("buo1-1-0", "BurningOil", "Black Ice", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo1-2-0", "BurningOil", "Black Ice", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo2-1-0", "BurningOil", "Cucumber Cantelope", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo2-2-0", "BurningOil", "Cucumber Cantelope", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo3-1-0", "BurningOil", "Cucumber Melon", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo3-2-0", "BurningOil", "Cucumber Melon", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo4-1-0", "BurningOil", "Fruit Loop", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo4-2-0", "BurningOil", "Fruit Loop", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo5-1-0", "BurningOil", "Hawaiian Breeze", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo5-2-0", "BurningOil", "Hawaiian Breeze", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo6-1-0", "BurningOil", "Jamaican Fruit", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo6-2-0", "BurningOil", "Jamaican Fruit", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo7-1-0", "BurningOil", "Jolly Rancher", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo7-2-0", "BurningOil", "Jolly Rancher", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo8-1-0", "BurningOil", "Kumquat", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo8-2-0", "BurningOil", "Kumquat", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo9-1-0", "BurningOil", "Mango Papaya", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo9-2-0", "BurningOil", "Mango Papaya", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo10-1-0", "BurningOil", "Peach Tree", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo10-2-0", "BurningOil", "Peach Tree", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo11-1-0", "BurningOil", "Sunwash Linen", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo11-2-0", "BurningOil", "Sunwash Linen", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo12-1-0", "BurningOil", "Pink Sands", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo12-2-0", "BurningOil", "Pink Sands", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo13-1-0", "BurningOil", "Tobacco Vanilla", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo13-2-0", "BurningOil", "Tobacco Vanilla", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo14-1-0", "BurningOil", "Mango Peach", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo14-2-0", "BurningOil", "Mango Peach", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo15-1-0", "BurningOil", "Cranberry", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo15-2-0", "BurningOil", "Cranberry", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo16-1-0", "BurningOil", "Spanish Lemon", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo16-2-0", "BurningOil", "Spanish Lemon", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),
("buo17-1-0", "BurningOil", "Champagne", "Burning Oil - 3oz", "dbImages/noImage.png", "15", "16.00"),
("buo17-2-0", "BurningOil", "Champagne", "Burning Oil with Burner - 3oz", "dbImages/noImage.png", "15", "30.00"),

("oob1-1-0", "OilBurner", "Oil Burner", "3oz - Oil Burner", "dbImages/oob1-1-0.png", "15", "16.00");



